# coding: utf-8

"""
    Registration-client-api

    Interage com o registration server (eureka) para registar esta instância ou obter servidores com o qual pode comunicar  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.endpoint import Endpoint  # noqa: E501
from swagger_client.rest import ApiException


class TestEndpoint(unittest.TestCase):
    """Endpoint unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEndpoint(self):
        """Test Endpoint"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.endpoint.Endpoint()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
