# coding: utf-8

# flake8: noqa

"""
    Registration-client-api

    Interage com o registration server (eureka) para registar esta instância ou obter servidores com o qual pode comunicar  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.endpoints_api import EndpointsApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.endpoint import Endpoint
