# coding: utf-8

# flake8: noqa
"""
    Registration-client-api

    Interage com o registration server (eureka) para registar esta instância ou obter servidores com o qual pode comunicar  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.endpoint import Endpoint
