# coding: utf-8

"""
    Registration-client-api

    Interage com o registration server (eureka) para registar esta instância ou obter servidores com o qual pode comunicar  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Endpoint(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'instance_id': 'str',
        'endpoint': 'str'
    }

    attribute_map = {
        'instance_id': 'instanceId',
        'endpoint': 'endpoint'
    }

    def __init__(self, instance_id=None, endpoint=None):  # noqa: E501
        """Endpoint - a model defined in Swagger"""  # noqa: E501

        self._instance_id = None
        self._endpoint = None
        self.discriminator = None

        if instance_id is not None:
            self.instance_id = instance_id
        if endpoint is not None:
            self.endpoint = endpoint

    @property
    def instance_id(self):
        """Gets the instance_id of this Endpoint.  # noqa: E501


        :return: The instance_id of this Endpoint.  # noqa: E501
        :rtype: str
        """
        return self._instance_id

    @instance_id.setter
    def instance_id(self, instance_id):
        """Sets the instance_id of this Endpoint.


        :param instance_id: The instance_id of this Endpoint.  # noqa: E501
        :type: str
        """

        self._instance_id = instance_id

    @property
    def endpoint(self):
        """Gets the endpoint of this Endpoint.  # noqa: E501


        :return: The endpoint of this Endpoint.  # noqa: E501
        :rtype: str
        """
        return self._endpoint

    @endpoint.setter
    def endpoint(self, endpoint):
        """Sets the endpoint of this Endpoint.


        :param endpoint: The endpoint of this Endpoint.  # noqa: E501
        :type: str
        """

        self._endpoint = endpoint

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Endpoint, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Endpoint):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
